ALTER TABLE activities ADD COLUMN IF NOT EXISTS average_cadence DOUBLE PRECISION;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS calories DOUBLE PRECISION;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS weighted_average_watts INTEGER;
